POST http://localhost:8000/trpc.test.online.Message/SendMessage
Content-Type: application/json

{
  "msg_content": "string",
  "msg_title": "string",
  "send_from": "raintao",
  "send_to": [
    "raintao"
  ]
}}